// Protocol Buffers schema for wasmib MIB model serialization.
// This schema is shared between Rust (prost) and Go code generation.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: proto/wasmib.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Root serialization envelope for FFI export.
type SerializedModel struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Schema version for forward compatibility.
	Version uint32 `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	// Optional fingerprint of source MIB files (for cache validation).
	// Empty bytes means no fingerprint.
	Fingerprint []byte `protobuf:"bytes,2,opt,name=fingerprint,proto3" json:"fingerprint,omitempty"`
	// Resolved modules.
	Modules []*SerializedModule `protobuf:"bytes,5,rep,name=modules,proto3" json:"modules,omitempty"`
	// OID tree nodes.
	Nodes []*SerializedNode `protobuf:"bytes,6,rep,name=nodes,proto3" json:"nodes,omitempty"`
	// Type definitions.
	Types []*SerializedType `protobuf:"bytes,7,rep,name=types,proto3" json:"types,omitempty"`
	// Object definitions.
	Objects []*SerializedObject `protobuf:"bytes,8,rep,name=objects,proto3" json:"objects,omitempty"`
	// Notification definitions.
	Notifications []*SerializedNotification `protobuf:"bytes,9,rep,name=notifications,proto3" json:"notifications,omitempty"`
	// Root node IDs (typically iso=1).
	Roots []uint32 `protobuf:"varint,10,rep,packed,name=roots,proto3" json:"roots,omitempty"`
	// Unresolved reference counts (for diagnostics).
	UnresolvedImports             uint32 `protobuf:"varint,11,opt,name=unresolved_imports,json=unresolvedImports,proto3" json:"unresolved_imports,omitempty"`
	UnresolvedTypes               uint32 `protobuf:"varint,12,opt,name=unresolved_types,json=unresolvedTypes,proto3" json:"unresolved_types,omitempty"`
	UnresolvedOids                uint32 `protobuf:"varint,13,opt,name=unresolved_oids,json=unresolvedOids,proto3" json:"unresolved_oids,omitempty"`
	UnresolvedIndexes             uint32 `protobuf:"varint,14,opt,name=unresolved_indexes,json=unresolvedIndexes,proto3" json:"unresolved_indexes,omitempty"`
	UnresolvedNotificationObjects uint32 `protobuf:"varint,15,opt,name=unresolved_notification_objects,json=unresolvedNotificationObjects,proto3" json:"unresolved_notification_objects,omitempty"`
	// Detailed unresolved references (for debugging).
	UnresolvedImportDetails []*UnresolvedImport             `protobuf:"bytes,16,rep,name=unresolved_import_details,json=unresolvedImportDetails,proto3" json:"unresolved_import_details,omitempty"`
	UnresolvedTypeDetails   []*UnresolvedType               `protobuf:"bytes,17,rep,name=unresolved_type_details,json=unresolvedTypeDetails,proto3" json:"unresolved_type_details,omitempty"`
	UnresolvedOidDetails    []*UnresolvedOid                `protobuf:"bytes,18,rep,name=unresolved_oid_details,json=unresolvedOidDetails,proto3" json:"unresolved_oid_details,omitempty"`
	UnresolvedIndexDetails  []*UnresolvedIndex              `protobuf:"bytes,19,rep,name=unresolved_index_details,json=unresolvedIndexDetails,proto3" json:"unresolved_index_details,omitempty"`
	UnresolvedNotifDetails  []*UnresolvedNotificationObject `protobuf:"bytes,20,rep,name=unresolved_notif_details,json=unresolvedNotifDetails,proto3" json:"unresolved_notif_details,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *SerializedModel) Reset() {
	*x = SerializedModel{}
	mi := &file_proto_wasmib_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SerializedModel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SerializedModel) ProtoMessage() {}

func (x *SerializedModel) ProtoReflect() protoreflect.Message {
	mi := &file_proto_wasmib_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SerializedModel.ProtoReflect.Descriptor instead.
func (*SerializedModel) Descriptor() ([]byte, []int) {
	return file_proto_wasmib_proto_rawDescGZIP(), []int{0}
}

func (x *SerializedModel) GetVersion() uint32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *SerializedModel) GetFingerprint() []byte {
	if x != nil {
		return x.Fingerprint
	}
	return nil
}

func (x *SerializedModel) GetModules() []*SerializedModule {
	if x != nil {
		return x.Modules
	}
	return nil
}

func (x *SerializedModel) GetNodes() []*SerializedNode {
	if x != nil {
		return x.Nodes
	}
	return nil
}

func (x *SerializedModel) GetTypes() []*SerializedType {
	if x != nil {
		return x.Types
	}
	return nil
}

func (x *SerializedModel) GetObjects() []*SerializedObject {
	if x != nil {
		return x.Objects
	}
	return nil
}

func (x *SerializedModel) GetNotifications() []*SerializedNotification {
	if x != nil {
		return x.Notifications
	}
	return nil
}

func (x *SerializedModel) GetRoots() []uint32 {
	if x != nil {
		return x.Roots
	}
	return nil
}

func (x *SerializedModel) GetUnresolvedImports() uint32 {
	if x != nil {
		return x.UnresolvedImports
	}
	return 0
}

func (x *SerializedModel) GetUnresolvedTypes() uint32 {
	if x != nil {
		return x.UnresolvedTypes
	}
	return 0
}

func (x *SerializedModel) GetUnresolvedOids() uint32 {
	if x != nil {
		return x.UnresolvedOids
	}
	return 0
}

func (x *SerializedModel) GetUnresolvedIndexes() uint32 {
	if x != nil {
		return x.UnresolvedIndexes
	}
	return 0
}

func (x *SerializedModel) GetUnresolvedNotificationObjects() uint32 {
	if x != nil {
		return x.UnresolvedNotificationObjects
	}
	return 0
}

func (x *SerializedModel) GetUnresolvedImportDetails() []*UnresolvedImport {
	if x != nil {
		return x.UnresolvedImportDetails
	}
	return nil
}

func (x *SerializedModel) GetUnresolvedTypeDetails() []*UnresolvedType {
	if x != nil {
		return x.UnresolvedTypeDetails
	}
	return nil
}

func (x *SerializedModel) GetUnresolvedOidDetails() []*UnresolvedOid {
	if x != nil {
		return x.UnresolvedOidDetails
	}
	return nil
}

func (x *SerializedModel) GetUnresolvedIndexDetails() []*UnresolvedIndex {
	if x != nil {
		return x.UnresolvedIndexDetails
	}
	return nil
}

func (x *SerializedModel) GetUnresolvedNotifDetails() []*UnresolvedNotificationObject {
	if x != nil {
		return x.UnresolvedNotifDetails
	}
	return nil
}

// Serialized module definition.
type SerializedModule struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Module name.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// LAST-UPDATED value (empty = none).
	LastUpdated string `protobuf:"bytes,2,opt,name=last_updated,json=lastUpdated,proto3" json:"last_updated,omitempty"`
	// CONTACT-INFO value (empty = none).
	ContactInfo string `protobuf:"bytes,3,opt,name=contact_info,json=contactInfo,proto3" json:"contact_info,omitempty"`
	// ORGANIZATION value (empty = none).
	Organization string `protobuf:"bytes,4,opt,name=organization,proto3" json:"organization,omitempty"`
	// Description text (empty = none).
	Description string `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	// Revision history.
	Revisions     []*SerializedRevision `protobuf:"bytes,6,rep,name=revisions,proto3" json:"revisions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SerializedModule) Reset() {
	*x = SerializedModule{}
	mi := &file_proto_wasmib_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SerializedModule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SerializedModule) ProtoMessage() {}

func (x *SerializedModule) ProtoReflect() protoreflect.Message {
	mi := &file_proto_wasmib_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SerializedModule.ProtoReflect.Descriptor instead.
func (*SerializedModule) Descriptor() ([]byte, []int) {
	return file_proto_wasmib_proto_rawDescGZIP(), []int{1}
}

func (x *SerializedModule) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SerializedModule) GetLastUpdated() string {
	if x != nil {
		return x.LastUpdated
	}
	return ""
}

func (x *SerializedModule) GetContactInfo() string {
	if x != nil {
		return x.ContactInfo
	}
	return ""
}

func (x *SerializedModule) GetOrganization() string {
	if x != nil {
		return x.Organization
	}
	return ""
}

func (x *SerializedModule) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *SerializedModule) GetRevisions() []*SerializedRevision {
	if x != nil {
		return x.Revisions
	}
	return nil
}

// Serialized revision entry.
type SerializedRevision struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Revision date.
	Date string `protobuf:"bytes,1,opt,name=date,proto3" json:"date,omitempty"`
	// Revision description.
	Description   string `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SerializedRevision) Reset() {
	*x = SerializedRevision{}
	mi := &file_proto_wasmib_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SerializedRevision) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SerializedRevision) ProtoMessage() {}

func (x *SerializedRevision) ProtoReflect() protoreflect.Message {
	mi := &file_proto_wasmib_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SerializedRevision.ProtoReflect.Descriptor instead.
func (*SerializedRevision) Descriptor() ([]byte, []int) {
	return file_proto_wasmib_proto_rawDescGZIP(), []int{2}
}

func (x *SerializedRevision) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *SerializedRevision) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

// Serialized OID tree node.
type SerializedNode struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The arc (subidentifier) at this position.
	Subid uint32 `protobuf:"varint,1,opt,name=subid,proto3" json:"subid,omitempty"`
	// Parent node (NodeId, 0 = none/root).
	Parent uint32 `protobuf:"varint,2,opt,name=parent,proto3" json:"parent,omitempty"`
	// Child nodes (Vec<NodeId>).
	Children []uint32 `protobuf:"varint,3,rep,packed,name=children,proto3" json:"children,omitempty"`
	// Node kind (0-9, see NodeKind enum).
	Kind uint32 `protobuf:"varint,4,opt,name=kind,proto3" json:"kind,omitempty"`
	// Definitions at this OID.
	Definitions   []*SerializedNodeDef `protobuf:"bytes,5,rep,name=definitions,proto3" json:"definitions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SerializedNode) Reset() {
	*x = SerializedNode{}
	mi := &file_proto_wasmib_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SerializedNode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SerializedNode) ProtoMessage() {}

func (x *SerializedNode) ProtoReflect() protoreflect.Message {
	mi := &file_proto_wasmib_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SerializedNode.ProtoReflect.Descriptor instead.
func (*SerializedNode) Descriptor() ([]byte, []int) {
	return file_proto_wasmib_proto_rawDescGZIP(), []int{3}
}

func (x *SerializedNode) GetSubid() uint32 {
	if x != nil {
		return x.Subid
	}
	return 0
}

func (x *SerializedNode) GetParent() uint32 {
	if x != nil {
		return x.Parent
	}
	return 0
}

func (x *SerializedNode) GetChildren() []uint32 {
	if x != nil {
		return x.Children
	}
	return nil
}

func (x *SerializedNode) GetKind() uint32 {
	if x != nil {
		return x.Kind
	}
	return 0
}

func (x *SerializedNode) GetDefinitions() []*SerializedNodeDef {
	if x != nil {
		return x.Definitions
	}
	return nil
}

// Serialized node definition.
type SerializedNodeDef struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Module where this definition appears (ModuleId).
	Module uint32 `protobuf:"varint,1,opt,name=module,proto3" json:"module,omitempty"`
	// Object name/label.
	Label string `protobuf:"bytes,2,opt,name=label,proto3" json:"label,omitempty"`
	// Associated object (ObjectId, 0 = none).
	Object uint32 `protobuf:"varint,3,opt,name=object,proto3" json:"object,omitempty"`
	// Associated notification (NotificationId, 0 = none).
	Notification  uint32 `protobuf:"varint,4,opt,name=notification,proto3" json:"notification,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SerializedNodeDef) Reset() {
	*x = SerializedNodeDef{}
	mi := &file_proto_wasmib_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SerializedNodeDef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SerializedNodeDef) ProtoMessage() {}

func (x *SerializedNodeDef) ProtoReflect() protoreflect.Message {
	mi := &file_proto_wasmib_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SerializedNodeDef.ProtoReflect.Descriptor instead.
func (*SerializedNodeDef) Descriptor() ([]byte, []int) {
	return file_proto_wasmib_proto_rawDescGZIP(), []int{4}
}

func (x *SerializedNodeDef) GetModule() uint32 {
	if x != nil {
		return x.Module
	}
	return 0
}

func (x *SerializedNodeDef) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *SerializedNodeDef) GetObject() uint32 {
	if x != nil {
		return x.Object
	}
	return 0
}

func (x *SerializedNodeDef) GetNotification() uint32 {
	if x != nil {
		return x.Notification
	}
	return 0
}

// Serialized object definition.
type SerializedObject struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Node in OID tree (NodeId).
	Node uint32 `protobuf:"varint,1,opt,name=node,proto3" json:"node,omitempty"`
	// Defining module (ModuleId).
	Module uint32 `protobuf:"varint,2,opt,name=module,proto3" json:"module,omitempty"`
	// Object name.
	Name string `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	// Resolved type (TypeId, 0 = unresolved).
	TypeId uint32 `protobuf:"varint,4,opt,name=type_id,json=typeId,proto3" json:"type_id,omitempty"`
	// Access level (0-5, see Access enum).
	Access uint32 `protobuf:"varint,5,opt,name=access,proto3" json:"access,omitempty"`
	// Definition status (0-2, see Status enum).
	Status uint32 `protobuf:"varint,6,opt,name=status,proto3" json:"status,omitempty"`
	// Description text (empty = none).
	Description string `protobuf:"bytes,7,opt,name=description,proto3" json:"description,omitempty"`
	// Units string (empty = none).
	Units string `protobuf:"bytes,8,opt,name=units,proto3" json:"units,omitempty"`
	// Reference text (empty = none).
	Reference string `protobuf:"bytes,9,opt,name=reference,proto3" json:"reference,omitempty"`
	// Index specification (for row objects).
	Index *SerializedIndex `protobuf:"bytes,10,opt,name=index,proto3,oneof" json:"index,omitempty"`
	// AUGMENTS target (NodeId, 0 = none).
	Augments uint32 `protobuf:"varint,11,opt,name=augments,proto3" json:"augments,omitempty"`
	// Default value.
	Defval *SerializedDefVal `protobuf:"bytes,12,opt,name=defval,proto3,oneof" json:"defval,omitempty"`
	// Inline enumeration values (not from type).
	InlineEnum []*EnumValue `protobuf:"bytes,13,rep,name=inline_enum,json=inlineEnum,proto3" json:"inline_enum,omitempty"`
	// Inline BITS values (not from type).
	InlineBits    []*BitDef `protobuf:"bytes,14,rep,name=inline_bits,json=inlineBits,proto3" json:"inline_bits,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SerializedObject) Reset() {
	*x = SerializedObject{}
	mi := &file_proto_wasmib_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SerializedObject) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SerializedObject) ProtoMessage() {}

func (x *SerializedObject) ProtoReflect() protoreflect.Message {
	mi := &file_proto_wasmib_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SerializedObject.ProtoReflect.Descriptor instead.
func (*SerializedObject) Descriptor() ([]byte, []int) {
	return file_proto_wasmib_proto_rawDescGZIP(), []int{5}
}

func (x *SerializedObject) GetNode() uint32 {
	if x != nil {
		return x.Node
	}
	return 0
}

func (x *SerializedObject) GetModule() uint32 {
	if x != nil {
		return x.Module
	}
	return 0
}

func (x *SerializedObject) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SerializedObject) GetTypeId() uint32 {
	if x != nil {
		return x.TypeId
	}
	return 0
}

func (x *SerializedObject) GetAccess() uint32 {
	if x != nil {
		return x.Access
	}
	return 0
}

func (x *SerializedObject) GetStatus() uint32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *SerializedObject) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *SerializedObject) GetUnits() string {
	if x != nil {
		return x.Units
	}
	return ""
}

func (x *SerializedObject) GetReference() string {
	if x != nil {
		return x.Reference
	}
	return ""
}

func (x *SerializedObject) GetIndex() *SerializedIndex {
	if x != nil {
		return x.Index
	}
	return nil
}

func (x *SerializedObject) GetAugments() uint32 {
	if x != nil {
		return x.Augments
	}
	return 0
}

func (x *SerializedObject) GetDefval() *SerializedDefVal {
	if x != nil {
		return x.Defval
	}
	return nil
}

func (x *SerializedObject) GetInlineEnum() []*EnumValue {
	if x != nil {
		return x.InlineEnum
	}
	return nil
}

func (x *SerializedObject) GetInlineBits() []*BitDef {
	if x != nil {
		return x.InlineBits
	}
	return nil
}

// Serialized index specification.
type SerializedIndex struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Index items.
	Items         []*SerializedIndexItem `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SerializedIndex) Reset() {
	*x = SerializedIndex{}
	mi := &file_proto_wasmib_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SerializedIndex) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SerializedIndex) ProtoMessage() {}

func (x *SerializedIndex) ProtoReflect() protoreflect.Message {
	mi := &file_proto_wasmib_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SerializedIndex.ProtoReflect.Descriptor instead.
func (*SerializedIndex) Descriptor() ([]byte, []int) {
	return file_proto_wasmib_proto_rawDescGZIP(), []int{6}
}

func (x *SerializedIndex) GetItems() []*SerializedIndexItem {
	if x != nil {
		return x.Items
	}
	return nil
}

// Serialized index item.
type SerializedIndexItem struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The index object node (NodeId).
	Object uint32 `protobuf:"varint,1,opt,name=object,proto3" json:"object,omitempty"`
	// Whether this index is IMPLIED.
	Implied       bool `protobuf:"varint,2,opt,name=implied,proto3" json:"implied,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SerializedIndexItem) Reset() {
	*x = SerializedIndexItem{}
	mi := &file_proto_wasmib_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SerializedIndexItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SerializedIndexItem) ProtoMessage() {}

func (x *SerializedIndexItem) ProtoReflect() protoreflect.Message {
	mi := &file_proto_wasmib_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SerializedIndexItem.ProtoReflect.Descriptor instead.
func (*SerializedIndexItem) Descriptor() ([]byte, []int) {
	return file_proto_wasmib_proto_rawDescGZIP(), []int{7}
}

func (x *SerializedIndexItem) GetObject() uint32 {
	if x != nil {
		return x.Object
	}
	return 0
}

func (x *SerializedIndexItem) GetImplied() bool {
	if x != nil {
		return x.Implied
	}
	return false
}

// Serialized default value.
type SerializedDefVal struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Kind: 0=Integer, 1=Unsigned, 2=String, 3=HexString, 4=BinaryString, 5=Enum, 6=Bits, 7=OidRef.
	Kind uint32 `protobuf:"varint,1,opt,name=kind,proto3" json:"kind,omitempty"`
	// Integer value (for kind 0).
	IntVal *int64 `protobuf:"varint,2,opt,name=int_val,json=intVal,proto3,oneof" json:"int_val,omitempty"`
	// Unsigned value (for kind 1).
	UintVal *uint64 `protobuf:"varint,3,opt,name=uint_val,json=uintVal,proto3,oneof" json:"uint_val,omitempty"`
	// String value (for kinds 2, 5, or unresolved OID symbol).
	StrVal *string `protobuf:"bytes,4,opt,name=str_val,json=strVal,proto3,oneof" json:"str_val,omitempty"`
	// Raw string (for kinds 3, 4 - hex/binary strings).
	RawStr *string `protobuf:"bytes,5,opt,name=raw_str,json=rawStr,proto3,oneof" json:"raw_str,omitempty"`
	// Node ID (for kind 7 - resolved OID ref).
	NodeVal *uint32 `protobuf:"varint,6,opt,name=node_val,json=nodeVal,proto3,oneof" json:"node_val,omitempty"`
	// Bit names (for kind 6).
	BitsVal       []string `protobuf:"bytes,7,rep,name=bits_val,json=bitsVal,proto3" json:"bits_val,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SerializedDefVal) Reset() {
	*x = SerializedDefVal{}
	mi := &file_proto_wasmib_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SerializedDefVal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SerializedDefVal) ProtoMessage() {}

func (x *SerializedDefVal) ProtoReflect() protoreflect.Message {
	mi := &file_proto_wasmib_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SerializedDefVal.ProtoReflect.Descriptor instead.
func (*SerializedDefVal) Descriptor() ([]byte, []int) {
	return file_proto_wasmib_proto_rawDescGZIP(), []int{8}
}

func (x *SerializedDefVal) GetKind() uint32 {
	if x != nil {
		return x.Kind
	}
	return 0
}

func (x *SerializedDefVal) GetIntVal() int64 {
	if x != nil && x.IntVal != nil {
		return *x.IntVal
	}
	return 0
}

func (x *SerializedDefVal) GetUintVal() uint64 {
	if x != nil && x.UintVal != nil {
		return *x.UintVal
	}
	return 0
}

func (x *SerializedDefVal) GetStrVal() string {
	if x != nil && x.StrVal != nil {
		return *x.StrVal
	}
	return ""
}

func (x *SerializedDefVal) GetRawStr() string {
	if x != nil && x.RawStr != nil {
		return *x.RawStr
	}
	return ""
}

func (x *SerializedDefVal) GetNodeVal() uint32 {
	if x != nil && x.NodeVal != nil {
		return *x.NodeVal
	}
	return 0
}

func (x *SerializedDefVal) GetBitsVal() []string {
	if x != nil {
		return x.BitsVal
	}
	return nil
}

// Serialized type definition.
type SerializedType struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Defining module (ModuleId).
	Module uint32 `protobuf:"varint,1,opt,name=module,proto3" json:"module,omitempty"`
	// Type name.
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// Base type (0-11, see BaseType enum).
	Base uint32 `protobuf:"varint,3,opt,name=base,proto3" json:"base,omitempty"`
	// Parent type (TypeId, 0 = none, for TC inheritance).
	Parent uint32 `protobuf:"varint,4,opt,name=parent,proto3" json:"parent,omitempty"`
	// Definition status (0-2, see Status enum).
	Status uint32 `protobuf:"varint,5,opt,name=status,proto3" json:"status,omitempty"`
	// Is this a textual convention?
	IsTc bool `protobuf:"varint,6,opt,name=is_tc,json=isTc,proto3" json:"is_tc,omitempty"`
	// Display hint (empty = none).
	Hint string `protobuf:"bytes,7,opt,name=hint,proto3" json:"hint,omitempty"`
	// Description text (empty = none).
	Description string `protobuf:"bytes,8,opt,name=description,proto3" json:"description,omitempty"`
	// Size constraint.
	Size *SerializedConstraint `protobuf:"bytes,9,opt,name=size,proto3,oneof" json:"size,omitempty"`
	// Value range constraint.
	Range *SerializedConstraint `protobuf:"bytes,10,opt,name=range,proto3,oneof" json:"range,omitempty"`
	// Enumeration values.
	EnumValues []*EnumValue `protobuf:"bytes,11,rep,name=enum_values,json=enumValues,proto3" json:"enum_values,omitempty"`
	// Bit definitions.
	BitDefs       []*BitDef `protobuf:"bytes,12,rep,name=bit_defs,json=bitDefs,proto3" json:"bit_defs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SerializedType) Reset() {
	*x = SerializedType{}
	mi := &file_proto_wasmib_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SerializedType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SerializedType) ProtoMessage() {}

func (x *SerializedType) ProtoReflect() protoreflect.Message {
	mi := &file_proto_wasmib_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SerializedType.ProtoReflect.Descriptor instead.
func (*SerializedType) Descriptor() ([]byte, []int) {
	return file_proto_wasmib_proto_rawDescGZIP(), []int{9}
}

func (x *SerializedType) GetModule() uint32 {
	if x != nil {
		return x.Module
	}
	return 0
}

func (x *SerializedType) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SerializedType) GetBase() uint32 {
	if x != nil {
		return x.Base
	}
	return 0
}

func (x *SerializedType) GetParent() uint32 {
	if x != nil {
		return x.Parent
	}
	return 0
}

func (x *SerializedType) GetStatus() uint32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *SerializedType) GetIsTc() bool {
	if x != nil {
		return x.IsTc
	}
	return false
}

func (x *SerializedType) GetHint() string {
	if x != nil {
		return x.Hint
	}
	return ""
}

func (x *SerializedType) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *SerializedType) GetSize() *SerializedConstraint {
	if x != nil {
		return x.Size
	}
	return nil
}

func (x *SerializedType) GetRange() *SerializedConstraint {
	if x != nil {
		return x.Range
	}
	return nil
}

func (x *SerializedType) GetEnumValues() []*EnumValue {
	if x != nil {
		return x.EnumValues
	}
	return nil
}

func (x *SerializedType) GetBitDefs() []*BitDef {
	if x != nil {
		return x.BitDefs
	}
	return nil
}

// Enumeration value: (value, name).
type EnumValue struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         int64                  `protobuf:"varint,1,opt,name=value,proto3" json:"value,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnumValue) Reset() {
	*x = EnumValue{}
	mi := &file_proto_wasmib_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnumValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnumValue) ProtoMessage() {}

func (x *EnumValue) ProtoReflect() protoreflect.Message {
	mi := &file_proto_wasmib_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnumValue.ProtoReflect.Descriptor instead.
func (*EnumValue) Descriptor() ([]byte, []int) {
	return file_proto_wasmib_proto_rawDescGZIP(), []int{10}
}

func (x *EnumValue) GetValue() int64 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *EnumValue) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// Bit definition: (position, name).
type BitDef struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Position      uint32                 `protobuf:"varint,1,opt,name=position,proto3" json:"position,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BitDef) Reset() {
	*x = BitDef{}
	mi := &file_proto_wasmib_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BitDef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BitDef) ProtoMessage() {}

func (x *BitDef) ProtoReflect() protoreflect.Message {
	mi := &file_proto_wasmib_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BitDef.ProtoReflect.Descriptor instead.
func (*BitDef) Descriptor() ([]byte, []int) {
	return file_proto_wasmib_proto_rawDescGZIP(), []int{11}
}

func (x *BitDef) GetPosition() uint32 {
	if x != nil {
		return x.Position
	}
	return 0
}

func (x *BitDef) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// Serialized constraint (for size or value ranges).
type SerializedConstraint struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// (min, max) pairs for allowed values/sizes.
	Ranges        []*Range `protobuf:"bytes,1,rep,name=ranges,proto3" json:"ranges,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SerializedConstraint) Reset() {
	*x = SerializedConstraint{}
	mi := &file_proto_wasmib_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SerializedConstraint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SerializedConstraint) ProtoMessage() {}

func (x *SerializedConstraint) ProtoReflect() protoreflect.Message {
	mi := &file_proto_wasmib_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SerializedConstraint.ProtoReflect.Descriptor instead.
func (*SerializedConstraint) Descriptor() ([]byte, []int) {
	return file_proto_wasmib_proto_rawDescGZIP(), []int{12}
}

func (x *SerializedConstraint) GetRanges() []*Range {
	if x != nil {
		return x.Ranges
	}
	return nil
}

// Range pair (min, max).
type Range struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Min           int64                  `protobuf:"varint,1,opt,name=min,proto3" json:"min,omitempty"`
	Max           int64                  `protobuf:"varint,2,opt,name=max,proto3" json:"max,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Range) Reset() {
	*x = Range{}
	mi := &file_proto_wasmib_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Range) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Range) ProtoMessage() {}

func (x *Range) ProtoReflect() protoreflect.Message {
	mi := &file_proto_wasmib_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Range.ProtoReflect.Descriptor instead.
func (*Range) Descriptor() ([]byte, []int) {
	return file_proto_wasmib_proto_rawDescGZIP(), []int{13}
}

func (x *Range) GetMin() int64 {
	if x != nil {
		return x.Min
	}
	return 0
}

func (x *Range) GetMax() int64 {
	if x != nil {
		return x.Max
	}
	return 0
}

// Diagnostic message (error or warning from parsing/resolution).
type Diagnostic struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Severity: 0=error, 1=warning.
	Severity uint32 `protobuf:"varint,1,opt,name=severity,proto3" json:"severity,omitempty"`
	// Human-readable message.
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	// Byte offset in source (start).
	Start uint32 `protobuf:"varint,3,opt,name=start,proto3" json:"start,omitempty"`
	// Byte offset in source (end).
	End           uint32 `protobuf:"varint,4,opt,name=end,proto3" json:"end,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Diagnostic) Reset() {
	*x = Diagnostic{}
	mi := &file_proto_wasmib_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Diagnostic) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Diagnostic) ProtoMessage() {}

func (x *Diagnostic) ProtoReflect() protoreflect.Message {
	mi := &file_proto_wasmib_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Diagnostic.ProtoReflect.Descriptor instead.
func (*Diagnostic) Descriptor() ([]byte, []int) {
	return file_proto_wasmib_proto_rawDescGZIP(), []int{14}
}

func (x *Diagnostic) GetSeverity() uint32 {
	if x != nil {
		return x.Severity
	}
	return 0
}

func (x *Diagnostic) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *Diagnostic) GetStart() uint32 {
	if x != nil {
		return x.Start
	}
	return 0
}

func (x *Diagnostic) GetEnd() uint32 {
	if x != nil {
		return x.End
	}
	return 0
}

// Collection of diagnostics.
type Diagnostics struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*Diagnostic          `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Diagnostics) Reset() {
	*x = Diagnostics{}
	mi := &file_proto_wasmib_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Diagnostics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Diagnostics) ProtoMessage() {}

func (x *Diagnostics) ProtoReflect() protoreflect.Message {
	mi := &file_proto_wasmib_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Diagnostics.ProtoReflect.Descriptor instead.
func (*Diagnostics) Descriptor() ([]byte, []int) {
	return file_proto_wasmib_proto_rawDescGZIP(), []int{15}
}

func (x *Diagnostics) GetItems() []*Diagnostic {
	if x != nil {
		return x.Items
	}
	return nil
}

// Serialized notification definition.
type SerializedNotification struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Node in OID tree (NodeId).
	Node uint32 `protobuf:"varint,1,opt,name=node,proto3" json:"node,omitempty"`
	// Defining module (ModuleId).
	Module uint32 `protobuf:"varint,2,opt,name=module,proto3" json:"module,omitempty"`
	// Notification name.
	Name string `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	// Definition status (0-2, see Status enum).
	Status uint32 `protobuf:"varint,4,opt,name=status,proto3" json:"status,omitempty"`
	// Description text (empty = none).
	Description string `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	// Reference text (empty = none).
	Reference string `protobuf:"bytes,6,opt,name=reference,proto3" json:"reference,omitempty"`
	// Objects included in the notification (Vec<NodeId>).
	Objects       []uint32 `protobuf:"varint,7,rep,packed,name=objects,proto3" json:"objects,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SerializedNotification) Reset() {
	*x = SerializedNotification{}
	mi := &file_proto_wasmib_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SerializedNotification) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SerializedNotification) ProtoMessage() {}

func (x *SerializedNotification) ProtoReflect() protoreflect.Message {
	mi := &file_proto_wasmib_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SerializedNotification.ProtoReflect.Descriptor instead.
func (*SerializedNotification) Descriptor() ([]byte, []int) {
	return file_proto_wasmib_proto_rawDescGZIP(), []int{16}
}

func (x *SerializedNotification) GetNode() uint32 {
	if x != nil {
		return x.Node
	}
	return 0
}

func (x *SerializedNotification) GetModule() uint32 {
	if x != nil {
		return x.Module
	}
	return 0
}

func (x *SerializedNotification) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SerializedNotification) GetStatus() uint32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *SerializedNotification) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *SerializedNotification) GetReference() string {
	if x != nil {
		return x.Reference
	}
	return ""
}

func (x *SerializedNotification) GetObjects() []uint32 {
	if x != nil {
		return x.Objects
	}
	return nil
}

// Unresolved import reference.
type UnresolvedImport struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Module requesting the import (ModuleId).
	ImportingModule uint32 `protobuf:"varint,1,opt,name=importing_module,json=importingModule,proto3" json:"importing_module,omitempty"`
	// Module being imported from (may not exist).
	FromModule string `protobuf:"bytes,2,opt,name=from_module,json=fromModule,proto3" json:"from_module,omitempty"`
	// Symbol being imported.
	Symbol string `protobuf:"bytes,3,opt,name=symbol,proto3" json:"symbol,omitempty"`
	// Reason: 0=ModuleNotFound, 1=SymbolNotExported.
	Reason        uint32 `protobuf:"varint,4,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnresolvedImport) Reset() {
	*x = UnresolvedImport{}
	mi := &file_proto_wasmib_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnresolvedImport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnresolvedImport) ProtoMessage() {}

func (x *UnresolvedImport) ProtoReflect() protoreflect.Message {
	mi := &file_proto_wasmib_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnresolvedImport.ProtoReflect.Descriptor instead.
func (*UnresolvedImport) Descriptor() ([]byte, []int) {
	return file_proto_wasmib_proto_rawDescGZIP(), []int{17}
}

func (x *UnresolvedImport) GetImportingModule() uint32 {
	if x != nil {
		return x.ImportingModule
	}
	return 0
}

func (x *UnresolvedImport) GetFromModule() string {
	if x != nil {
		return x.FromModule
	}
	return ""
}

func (x *UnresolvedImport) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *UnresolvedImport) GetReason() uint32 {
	if x != nil {
		return x.Reason
	}
	return 0
}

// Unresolved type reference.
type UnresolvedType struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Module containing the reference (ModuleId).
	Module uint32 `protobuf:"varint,1,opt,name=module,proto3" json:"module,omitempty"`
	// Definition referencing the type.
	Referrer string `protobuf:"bytes,2,opt,name=referrer,proto3" json:"referrer,omitempty"`
	// Type being referenced.
	Referenced    string `protobuf:"bytes,3,opt,name=referenced,proto3" json:"referenced,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnresolvedType) Reset() {
	*x = UnresolvedType{}
	mi := &file_proto_wasmib_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnresolvedType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnresolvedType) ProtoMessage() {}

func (x *UnresolvedType) ProtoReflect() protoreflect.Message {
	mi := &file_proto_wasmib_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnresolvedType.ProtoReflect.Descriptor instead.
func (*UnresolvedType) Descriptor() ([]byte, []int) {
	return file_proto_wasmib_proto_rawDescGZIP(), []int{18}
}

func (x *UnresolvedType) GetModule() uint32 {
	if x != nil {
		return x.Module
	}
	return 0
}

func (x *UnresolvedType) GetReferrer() string {
	if x != nil {
		return x.Referrer
	}
	return ""
}

func (x *UnresolvedType) GetReferenced() string {
	if x != nil {
		return x.Referenced
	}
	return ""
}

// Unresolved OID component.
type UnresolvedOid struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Module containing the definition (ModuleId).
	Module uint32 `protobuf:"varint,1,opt,name=module,proto3" json:"module,omitempty"`
	// Definition with the OID.
	Definition string `protobuf:"bytes,2,opt,name=definition,proto3" json:"definition,omitempty"`
	// Unresolved component name.
	Component     string `protobuf:"bytes,3,opt,name=component,proto3" json:"component,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnresolvedOid) Reset() {
	*x = UnresolvedOid{}
	mi := &file_proto_wasmib_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnresolvedOid) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnresolvedOid) ProtoMessage() {}

func (x *UnresolvedOid) ProtoReflect() protoreflect.Message {
	mi := &file_proto_wasmib_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnresolvedOid.ProtoReflect.Descriptor instead.
func (*UnresolvedOid) Descriptor() ([]byte, []int) {
	return file_proto_wasmib_proto_rawDescGZIP(), []int{19}
}

func (x *UnresolvedOid) GetModule() uint32 {
	if x != nil {
		return x.Module
	}
	return 0
}

func (x *UnresolvedOid) GetDefinition() string {
	if x != nil {
		return x.Definition
	}
	return ""
}

func (x *UnresolvedOid) GetComponent() string {
	if x != nil {
		return x.Component
	}
	return ""
}

// Unresolved index object.
type UnresolvedIndex struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Module containing the row (ModuleId).
	Module uint32 `protobuf:"varint,1,opt,name=module,proto3" json:"module,omitempty"`
	// Row definition name.
	Row string `protobuf:"bytes,2,opt,name=row,proto3" json:"row,omitempty"`
	// Unresolved index object name.
	IndexObject   string `protobuf:"bytes,3,opt,name=index_object,json=indexObject,proto3" json:"index_object,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnresolvedIndex) Reset() {
	*x = UnresolvedIndex{}
	mi := &file_proto_wasmib_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnresolvedIndex) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnresolvedIndex) ProtoMessage() {}

func (x *UnresolvedIndex) ProtoReflect() protoreflect.Message {
	mi := &file_proto_wasmib_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnresolvedIndex.ProtoReflect.Descriptor instead.
func (*UnresolvedIndex) Descriptor() ([]byte, []int) {
	return file_proto_wasmib_proto_rawDescGZIP(), []int{20}
}

func (x *UnresolvedIndex) GetModule() uint32 {
	if x != nil {
		return x.Module
	}
	return 0
}

func (x *UnresolvedIndex) GetRow() string {
	if x != nil {
		return x.Row
	}
	return ""
}

func (x *UnresolvedIndex) GetIndexObject() string {
	if x != nil {
		return x.IndexObject
	}
	return ""
}

// Unresolved notification object.
type UnresolvedNotificationObject struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Module containing the notification (ModuleId).
	Module uint32 `protobuf:"varint,1,opt,name=module,proto3" json:"module,omitempty"`
	// Notification definition name.
	Notification string `protobuf:"bytes,2,opt,name=notification,proto3" json:"notification,omitempty"`
	// Unresolved object name.
	Object        string `protobuf:"bytes,3,opt,name=object,proto3" json:"object,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnresolvedNotificationObject) Reset() {
	*x = UnresolvedNotificationObject{}
	mi := &file_proto_wasmib_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnresolvedNotificationObject) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnresolvedNotificationObject) ProtoMessage() {}

func (x *UnresolvedNotificationObject) ProtoReflect() protoreflect.Message {
	mi := &file_proto_wasmib_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnresolvedNotificationObject.ProtoReflect.Descriptor instead.
func (*UnresolvedNotificationObject) Descriptor() ([]byte, []int) {
	return file_proto_wasmib_proto_rawDescGZIP(), []int{21}
}

func (x *UnresolvedNotificationObject) GetModule() uint32 {
	if x != nil {
		return x.Module
	}
	return 0
}

func (x *UnresolvedNotificationObject) GetNotification() string {
	if x != nil {
		return x.Notification
	}
	return ""
}

func (x *UnresolvedNotificationObject) GetObject() string {
	if x != nil {
		return x.Object
	}
	return ""
}

var File_proto_wasmib_proto protoreflect.FileDescriptor

const file_proto_wasmib_proto_rawDesc = "" +
	"\n" +
	"\x12proto/wasmib.proto\x12\x06wasmib\"\x8d\b\n" +
	"\x0fSerializedModel\x12\x18\n" +
	"\aversion\x18\x01 \x01(\rR\aversion\x12 \n" +
	"\vfingerprint\x18\x02 \x01(\fR\vfingerprint\x122\n" +
	"\amodules\x18\x05 \x03(\v2\x18.wasmib.SerializedModuleR\amodules\x12,\n" +
	"\x05nodes\x18\x06 \x03(\v2\x16.wasmib.SerializedNodeR\x05nodes\x12,\n" +
	"\x05types\x18\a \x03(\v2\x16.wasmib.SerializedTypeR\x05types\x122\n" +
	"\aobjects\x18\b \x03(\v2\x18.wasmib.SerializedObjectR\aobjects\x12D\n" +
	"\rnotifications\x18\t \x03(\v2\x1e.wasmib.SerializedNotificationR\rnotifications\x12\x14\n" +
	"\x05roots\x18\n" +
	" \x03(\rR\x05roots\x12-\n" +
	"\x12unresolved_imports\x18\v \x01(\rR\x11unresolvedImports\x12)\n" +
	"\x10unresolved_types\x18\f \x01(\rR\x0funresolvedTypes\x12'\n" +
	"\x0funresolved_oids\x18\r \x01(\rR\x0eunresolvedOids\x12-\n" +
	"\x12unresolved_indexes\x18\x0e \x01(\rR\x11unresolvedIndexes\x12F\n" +
	"\x1funresolved_notification_objects\x18\x0f \x01(\rR\x1dunresolvedNotificationObjects\x12T\n" +
	"\x19unresolved_import_details\x18\x10 \x03(\v2\x18.wasmib.UnresolvedImportR\x17unresolvedImportDetails\x12N\n" +
	"\x17unresolved_type_details\x18\x11 \x03(\v2\x16.wasmib.UnresolvedTypeR\x15unresolvedTypeDetails\x12K\n" +
	"\x16unresolved_oid_details\x18\x12 \x03(\v2\x15.wasmib.UnresolvedOidR\x14unresolvedOidDetails\x12Q\n" +
	"\x18unresolved_index_details\x18\x13 \x03(\v2\x17.wasmib.UnresolvedIndexR\x16unresolvedIndexDetails\x12^\n" +
	"\x18unresolved_notif_details\x18\x14 \x03(\v2$.wasmib.UnresolvedNotificationObjectR\x16unresolvedNotifDetails\"\xec\x01\n" +
	"\x10SerializedModule\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12!\n" +
	"\flast_updated\x18\x02 \x01(\tR\vlastUpdated\x12!\n" +
	"\fcontact_info\x18\x03 \x01(\tR\vcontactInfo\x12\"\n" +
	"\forganization\x18\x04 \x01(\tR\forganization\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\x128\n" +
	"\trevisions\x18\x06 \x03(\v2\x1a.wasmib.SerializedRevisionR\trevisions\"J\n" +
	"\x12SerializedRevision\x12\x12\n" +
	"\x04date\x18\x01 \x01(\tR\x04date\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\"\xab\x01\n" +
	"\x0eSerializedNode\x12\x14\n" +
	"\x05subid\x18\x01 \x01(\rR\x05subid\x12\x16\n" +
	"\x06parent\x18\x02 \x01(\rR\x06parent\x12\x1a\n" +
	"\bchildren\x18\x03 \x03(\rR\bchildren\x12\x12\n" +
	"\x04kind\x18\x04 \x01(\rR\x04kind\x12;\n" +
	"\vdefinitions\x18\x05 \x03(\v2\x19.wasmib.SerializedNodeDefR\vdefinitions\"}\n" +
	"\x11SerializedNodeDef\x12\x16\n" +
	"\x06module\x18\x01 \x01(\rR\x06module\x12\x14\n" +
	"\x05label\x18\x02 \x01(\tR\x05label\x12\x16\n" +
	"\x06object\x18\x03 \x01(\rR\x06object\x12\"\n" +
	"\fnotification\x18\x04 \x01(\rR\fnotification\"\xf2\x03\n" +
	"\x10SerializedObject\x12\x12\n" +
	"\x04node\x18\x01 \x01(\rR\x04node\x12\x16\n" +
	"\x06module\x18\x02 \x01(\rR\x06module\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x17\n" +
	"\atype_id\x18\x04 \x01(\rR\x06typeId\x12\x16\n" +
	"\x06access\x18\x05 \x01(\rR\x06access\x12\x16\n" +
	"\x06status\x18\x06 \x01(\rR\x06status\x12 \n" +
	"\vdescription\x18\a \x01(\tR\vdescription\x12\x14\n" +
	"\x05units\x18\b \x01(\tR\x05units\x12\x1c\n" +
	"\treference\x18\t \x01(\tR\treference\x122\n" +
	"\x05index\x18\n" +
	" \x01(\v2\x17.wasmib.SerializedIndexH\x00R\x05index\x88\x01\x01\x12\x1a\n" +
	"\baugments\x18\v \x01(\rR\baugments\x125\n" +
	"\x06defval\x18\f \x01(\v2\x18.wasmib.SerializedDefValH\x01R\x06defval\x88\x01\x01\x122\n" +
	"\vinline_enum\x18\r \x03(\v2\x11.wasmib.EnumValueR\n" +
	"inlineEnum\x12/\n" +
	"\vinline_bits\x18\x0e \x03(\v2\x0e.wasmib.BitDefR\n" +
	"inlineBitsB\b\n" +
	"\x06_indexB\t\n" +
	"\a_defval\"D\n" +
	"\x0fSerializedIndex\x121\n" +
	"\x05items\x18\x01 \x03(\v2\x1b.wasmib.SerializedIndexItemR\x05items\"G\n" +
	"\x13SerializedIndexItem\x12\x16\n" +
	"\x06object\x18\x01 \x01(\rR\x06object\x12\x18\n" +
	"\aimplied\x18\x02 \x01(\bR\aimplied\"\x99\x02\n" +
	"\x10SerializedDefVal\x12\x12\n" +
	"\x04kind\x18\x01 \x01(\rR\x04kind\x12\x1c\n" +
	"\aint_val\x18\x02 \x01(\x03H\x00R\x06intVal\x88\x01\x01\x12\x1e\n" +
	"\buint_val\x18\x03 \x01(\x04H\x01R\auintVal\x88\x01\x01\x12\x1c\n" +
	"\astr_val\x18\x04 \x01(\tH\x02R\x06strVal\x88\x01\x01\x12\x1c\n" +
	"\araw_str\x18\x05 \x01(\tH\x03R\x06rawStr\x88\x01\x01\x12\x1e\n" +
	"\bnode_val\x18\x06 \x01(\rH\x04R\anodeVal\x88\x01\x01\x12\x19\n" +
	"\bbits_val\x18\a \x03(\tR\abitsValB\n" +
	"\n" +
	"\b_int_valB\v\n" +
	"\t_uint_valB\n" +
	"\n" +
	"\b_str_valB\n" +
	"\n" +
	"\b_raw_strB\v\n" +
	"\t_node_val\"\xad\x03\n" +
	"\x0eSerializedType\x12\x16\n" +
	"\x06module\x18\x01 \x01(\rR\x06module\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04base\x18\x03 \x01(\rR\x04base\x12\x16\n" +
	"\x06parent\x18\x04 \x01(\rR\x06parent\x12\x16\n" +
	"\x06status\x18\x05 \x01(\rR\x06status\x12\x13\n" +
	"\x05is_tc\x18\x06 \x01(\bR\x04isTc\x12\x12\n" +
	"\x04hint\x18\a \x01(\tR\x04hint\x12 \n" +
	"\vdescription\x18\b \x01(\tR\vdescription\x125\n" +
	"\x04size\x18\t \x01(\v2\x1c.wasmib.SerializedConstraintH\x00R\x04size\x88\x01\x01\x127\n" +
	"\x05range\x18\n" +
	" \x01(\v2\x1c.wasmib.SerializedConstraintH\x01R\x05range\x88\x01\x01\x122\n" +
	"\venum_values\x18\v \x03(\v2\x11.wasmib.EnumValueR\n" +
	"enumValues\x12)\n" +
	"\bbit_defs\x18\f \x03(\v2\x0e.wasmib.BitDefR\abitDefsB\a\n" +
	"\x05_sizeB\b\n" +
	"\x06_range\"5\n" +
	"\tEnumValue\x12\x14\n" +
	"\x05value\x18\x01 \x01(\x03R\x05value\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"8\n" +
	"\x06BitDef\x12\x1a\n" +
	"\bposition\x18\x01 \x01(\rR\bposition\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"=\n" +
	"\x14SerializedConstraint\x12%\n" +
	"\x06ranges\x18\x01 \x03(\v2\r.wasmib.RangeR\x06ranges\"+\n" +
	"\x05Range\x12\x10\n" +
	"\x03min\x18\x01 \x01(\x03R\x03min\x12\x10\n" +
	"\x03max\x18\x02 \x01(\x03R\x03max\"j\n" +
	"\n" +
	"Diagnostic\x12\x1a\n" +
	"\bseverity\x18\x01 \x01(\rR\bseverity\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x14\n" +
	"\x05start\x18\x03 \x01(\rR\x05start\x12\x10\n" +
	"\x03end\x18\x04 \x01(\rR\x03end\"7\n" +
	"\vDiagnostics\x12(\n" +
	"\x05items\x18\x01 \x03(\v2\x12.wasmib.DiagnosticR\x05items\"\xca\x01\n" +
	"\x16SerializedNotification\x12\x12\n" +
	"\x04node\x18\x01 \x01(\rR\x04node\x12\x16\n" +
	"\x06module\x18\x02 \x01(\rR\x06module\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x16\n" +
	"\x06status\x18\x04 \x01(\rR\x06status\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\x12\x1c\n" +
	"\treference\x18\x06 \x01(\tR\treference\x12\x18\n" +
	"\aobjects\x18\a \x03(\rR\aobjects\"\x8e\x01\n" +
	"\x10UnresolvedImport\x12)\n" +
	"\x10importing_module\x18\x01 \x01(\rR\x0fimportingModule\x12\x1f\n" +
	"\vfrom_module\x18\x02 \x01(\tR\n" +
	"fromModule\x12\x16\n" +
	"\x06symbol\x18\x03 \x01(\tR\x06symbol\x12\x16\n" +
	"\x06reason\x18\x04 \x01(\rR\x06reason\"d\n" +
	"\x0eUnresolvedType\x12\x16\n" +
	"\x06module\x18\x01 \x01(\rR\x06module\x12\x1a\n" +
	"\breferrer\x18\x02 \x01(\tR\breferrer\x12\x1e\n" +
	"\n" +
	"referenced\x18\x03 \x01(\tR\n" +
	"referenced\"e\n" +
	"\rUnresolvedOid\x12\x16\n" +
	"\x06module\x18\x01 \x01(\rR\x06module\x12\x1e\n" +
	"\n" +
	"definition\x18\x02 \x01(\tR\n" +
	"definition\x12\x1c\n" +
	"\tcomponent\x18\x03 \x01(\tR\tcomponent\"^\n" +
	"\x0fUnresolvedIndex\x12\x16\n" +
	"\x06module\x18\x01 \x01(\rR\x06module\x12\x10\n" +
	"\x03row\x18\x02 \x01(\tR\x03row\x12!\n" +
	"\findex_object\x18\x03 \x01(\tR\vindexObject\"r\n" +
	"\x1cUnresolvedNotificationObject\x12\x16\n" +
	"\x06module\x18\x01 \x01(\rR\x06module\x12\"\n" +
	"\fnotification\x18\x02 \x01(\tR\fnotification\x12\x16\n" +
	"\x06object\x18\x03 \x01(\tR\x06objectB*Z(github.com/lukeod/wasmib/wasmib-go/protob\x06proto3"

var (
	file_proto_wasmib_proto_rawDescOnce sync.Once
	file_proto_wasmib_proto_rawDescData []byte
)

func file_proto_wasmib_proto_rawDescGZIP() []byte {
	file_proto_wasmib_proto_rawDescOnce.Do(func() {
		file_proto_wasmib_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_wasmib_proto_rawDesc), len(file_proto_wasmib_proto_rawDesc)))
	})
	return file_proto_wasmib_proto_rawDescData
}

var file_proto_wasmib_proto_msgTypes = make([]protoimpl.MessageInfo, 22)
var file_proto_wasmib_proto_goTypes = []any{
	(*SerializedModel)(nil),              // 0: wasmib.SerializedModel
	(*SerializedModule)(nil),             // 1: wasmib.SerializedModule
	(*SerializedRevision)(nil),           // 2: wasmib.SerializedRevision
	(*SerializedNode)(nil),               // 3: wasmib.SerializedNode
	(*SerializedNodeDef)(nil),            // 4: wasmib.SerializedNodeDef
	(*SerializedObject)(nil),             // 5: wasmib.SerializedObject
	(*SerializedIndex)(nil),              // 6: wasmib.SerializedIndex
	(*SerializedIndexItem)(nil),          // 7: wasmib.SerializedIndexItem
	(*SerializedDefVal)(nil),             // 8: wasmib.SerializedDefVal
	(*SerializedType)(nil),               // 9: wasmib.SerializedType
	(*EnumValue)(nil),                    // 10: wasmib.EnumValue
	(*BitDef)(nil),                       // 11: wasmib.BitDef
	(*SerializedConstraint)(nil),         // 12: wasmib.SerializedConstraint
	(*Range)(nil),                        // 13: wasmib.Range
	(*Diagnostic)(nil),                   // 14: wasmib.Diagnostic
	(*Diagnostics)(nil),                  // 15: wasmib.Diagnostics
	(*SerializedNotification)(nil),       // 16: wasmib.SerializedNotification
	(*UnresolvedImport)(nil),             // 17: wasmib.UnresolvedImport
	(*UnresolvedType)(nil),               // 18: wasmib.UnresolvedType
	(*UnresolvedOid)(nil),                // 19: wasmib.UnresolvedOid
	(*UnresolvedIndex)(nil),              // 20: wasmib.UnresolvedIndex
	(*UnresolvedNotificationObject)(nil), // 21: wasmib.UnresolvedNotificationObject
}
var file_proto_wasmib_proto_depIdxs = []int32{
	1,  // 0: wasmib.SerializedModel.modules:type_name -> wasmib.SerializedModule
	3,  // 1: wasmib.SerializedModel.nodes:type_name -> wasmib.SerializedNode
	9,  // 2: wasmib.SerializedModel.types:type_name -> wasmib.SerializedType
	5,  // 3: wasmib.SerializedModel.objects:type_name -> wasmib.SerializedObject
	16, // 4: wasmib.SerializedModel.notifications:type_name -> wasmib.SerializedNotification
	17, // 5: wasmib.SerializedModel.unresolved_import_details:type_name -> wasmib.UnresolvedImport
	18, // 6: wasmib.SerializedModel.unresolved_type_details:type_name -> wasmib.UnresolvedType
	19, // 7: wasmib.SerializedModel.unresolved_oid_details:type_name -> wasmib.UnresolvedOid
	20, // 8: wasmib.SerializedModel.unresolved_index_details:type_name -> wasmib.UnresolvedIndex
	21, // 9: wasmib.SerializedModel.unresolved_notif_details:type_name -> wasmib.UnresolvedNotificationObject
	2,  // 10: wasmib.SerializedModule.revisions:type_name -> wasmib.SerializedRevision
	4,  // 11: wasmib.SerializedNode.definitions:type_name -> wasmib.SerializedNodeDef
	6,  // 12: wasmib.SerializedObject.index:type_name -> wasmib.SerializedIndex
	8,  // 13: wasmib.SerializedObject.defval:type_name -> wasmib.SerializedDefVal
	10, // 14: wasmib.SerializedObject.inline_enum:type_name -> wasmib.EnumValue
	11, // 15: wasmib.SerializedObject.inline_bits:type_name -> wasmib.BitDef
	7,  // 16: wasmib.SerializedIndex.items:type_name -> wasmib.SerializedIndexItem
	12, // 17: wasmib.SerializedType.size:type_name -> wasmib.SerializedConstraint
	12, // 18: wasmib.SerializedType.range:type_name -> wasmib.SerializedConstraint
	10, // 19: wasmib.SerializedType.enum_values:type_name -> wasmib.EnumValue
	11, // 20: wasmib.SerializedType.bit_defs:type_name -> wasmib.BitDef
	13, // 21: wasmib.SerializedConstraint.ranges:type_name -> wasmib.Range
	14, // 22: wasmib.Diagnostics.items:type_name -> wasmib.Diagnostic
	23, // [23:23] is the sub-list for method output_type
	23, // [23:23] is the sub-list for method input_type
	23, // [23:23] is the sub-list for extension type_name
	23, // [23:23] is the sub-list for extension extendee
	0,  // [0:23] is the sub-list for field type_name
}

func init() { file_proto_wasmib_proto_init() }
func file_proto_wasmib_proto_init() {
	if File_proto_wasmib_proto != nil {
		return
	}
	file_proto_wasmib_proto_msgTypes[5].OneofWrappers = []any{}
	file_proto_wasmib_proto_msgTypes[8].OneofWrappers = []any{}
	file_proto_wasmib_proto_msgTypes[9].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_wasmib_proto_rawDesc), len(file_proto_wasmib_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   22,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_wasmib_proto_goTypes,
		DependencyIndexes: file_proto_wasmib_proto_depIdxs,
		MessageInfos:      file_proto_wasmib_proto_msgTypes,
	}.Build()
	File_proto_wasmib_proto = out.File
	file_proto_wasmib_proto_goTypes = nil
	file_proto_wasmib_proto_depIdxs = nil
}
